//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace roomscheduler.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBEfCoreEntities : DbContext
    {
        public DBEfCoreEntities()
            : base("name=DBEfCoreEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<book> books { get; set; }
        public virtual DbSet<MyDetail> MyDetails { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<tblLeave> tblLeaves { get; set; }
        public virtual DbSet<TblUser> TblUsers { get; set; }
    }
}
