//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace roomscheduler.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblLeave
    {
        public int Id { get; set; }
        public string EmployeeId { get; set; }
        public string EmployeeName { get; set; }
        public string Department { get; set; }
        public Nullable<int> ReasonId { get; set; }
        public Nullable<System.DateTime> LastDayWorked { get; set; }
        public Nullable<System.DateTime> EffectiveDate { get; set; }
        public Nullable<System.DateTime> ExpectedDate { get; set; }
        public Nullable<bool> Medical { get; set; }
        public Nullable<bool> Dental { get; set; }
        public Nullable<bool> Vision { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<bool> BirthAdoption { get; set; }
        public Nullable<bool> CareForSeriously { get; set; }
        public Nullable<bool> OwnSerious { get; set; }
        public Nullable<bool> Qulifly { get; set; }
        public Nullable<bool> Line { get; set; }
    }
}
